[package]
name = "onnx_inference"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.20.0", features = ["extension-module"] }
tract-onnx = "0.20.22"
anyhow = "1.0"

[lib]
name = "onnx_inference"
crate-type = ["cdylib"]

[[bin]]
name = "binary"
path = "src/main.rs"